name: valotracker_pro_v5
description: Application Flutter de base pour test d'intégration plugins modernes.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^10.0.0
  google_sign_in: ^7.2.0
  google_mobile_ads: ^5.1.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Décommente et adapte si tu utilises des assets :
  # assets:
  #   - assets/
  # Décommente si tu utilises des polices personnalisées :
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: fonts/MyCustomFont-Regular.ttf
